openapi: 3.0.3
info:
  title: Onboarding API
  version: '1.2'
  description: STD22045
  contact:
    email: hei.lovatiana@gmail.com
servers:
  - url: http://STD22045.com

components:
  schemas:
    Student:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        birthdate:
          type: string

paths:
  /students:
    get:
      summary: Get all students
      operationId: getAllStudents
      responses:
        '200':
          description: Successfully
          content:
            application/json:
              examples:
                students:
                  value:
                    - id: 1
                      name: lova
                      birthdate: 2000-01-01
                    - id: 2
                      name: tiana
                      birthdate: 2000-02-02
                    - id: 3
                      name: ntsoa
                      birthdate: 2000-03-03

    post:
      summary: Add a new student
      operationId: addStudent
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Student'
      responses:
        '201':
          description: Add student successfully
          content:
            application/json:
              examples:
                student:
                  value:
                    id: 4
                    name: bozy
                    birthdate: 2000-04-04
